version: "3.8"

services:
  telegram-bot-api:
    image: aiogram/telegram-bot-api:latest
    container_name: telegram-bot-api
    restart: unless-stopped
    ports:
      - "8081:8081"
    volumes:
      - ./telegram-bot-api-data:/var/lib/telegram-bot-api
    environment:
      TELEGRAM_API_ID: "СЮДА-ВСТАВЬ-API-ID"
      TELEGRAM_API_HASH: "СЮДА-ВСТАВЬ-API-HASH"
      TELEGRAM_LOCAL: "true"
      TELEGRAM_STAT: "false"
      TELEGRAM_LOG_VERBOSITY: "1"
      TELEGRAM_HTTP_PORT: "8081"